version: 2.1

jobs:
  build-libpdraw:
    docker:
      - image: ubuntu:focal
    steps:
      - checkout
      - run:
          name: "Install development packages"
          command: "apt update && apt install -y build-essential cmake"
      - run:
          name: "Make build directory"
          command: "mkdir build"
      - run:
          name: "CMake build files"
          command: "cd build && cmake -DCMAKE_BUILD_TYPE=1 ../"
      - run:
          name: "Build Project"
          command: "make"

workflows:
  build-libpdraw-workflow:
    jobs:
      - build-libpdraw
